services:
  python:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - app-tier
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-tier
    ports:
      - 27017:27017

networks:
  app-tier:
    driver: bridge

